filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'vendor/*'
        - 'app/Tests/*'

before_commands:
    - 'composer install --no-interaction --no-scripts'

checks:
    php:
        code_rating: true
        duplication: true

#build:
#    tests:
#        override:
#            -
#                command: 'phpunit app/Tests'
application:
    environment:
        php:
            version: 5.4.28